/**
 * AI BANKER TRANSFORMATION COPILOT
 * Phase 5C: Transformation Assessment Automated Verification Test Suite
 *
 * Validates the test specifications:
 * 1. 8 Dimensions defined with weights summing strictly to 1.00 (100%)
 * 2. Question bank contains exactly 24 questions (3 per dimension)
 * 3. Deterministic calculation: Lowest answers map to "AI Explorer" (0–24)
 * 4. Deterministic calculation: Highest answers map to "AI Transformation Leader" (80–100)
 * 5. Deterministic calculation: Balanced answers produce mathematically sound intermediate score
 * 6. Deterministic scoring throws on missing questions or incorrect question count
 * 7. Deterministic scoring rejects duplicate question answers
 * 8. Sensitive Credit Card PAN is detected and blocked prior to LLM transmission
 * 9. Sensitive SSN / PIN / Password is detected and blocked prior to LLM transmission
 * 10. Client-side detectSensitiveData flags sensitive financial patterns
 * 11. Endpoint /api/ai/transformation-assessment is mounted in server.ts
 * 12. Endpoint is protected by authenticateFirebaseToken middleware
 * 13. Missing or blank role is rejected with HTTP 400
 * 14. Missing or blank experienceLevel is rejected with HTTP 400
 * 15. Missing or blank businessArea is rejected with HTTP 400
 * 16. Incomplete answers array is rejected with HTTP 400
 * 17. Server guarantees deterministic scoring is immutable and not generated by Gemini
 * 18. System instruction mandates ADVISORY ONLY and non-decision use
 * 19. System instruction mandates prompt injection defense and data isolation
 * 20. Output parser handles clean JSON and markdown-fenced ```json ``` blocks
 * 21. Resilient fallback interpretation provided if Gemini fails
 * 22. TransformationAssessment.tsx provides 8-dimension multi-step navigation
 * 23. TransformationAssessment.tsx renders 24 rich interactive question cards
 * 24. TransformationAssessment.tsx renders comprehensive Results Dashboard with 8 dimension meters
 * 25. Results dashboard displays Strengths, Priorities, Recommendations, Quick Wins, Governance Focus
 * 26. Advisory and non-decision governance warnings are prominently displayed
 * 27. Dashboard.tsx integrates Transformation Assessment with LIVE status and phase 5
 * 28. Dashboard Overview quick action button launches Transformation Assessment
 * 29. SessionHistory.tsx supports transformation_assessment filter and type
 * 30. firestore.rules validates transformation_assessment in isValidInteraction
 * 31. firebase-blueprint.json registers transformation_assessment
 * 32. Regression check: Process Optimizer remains intact
 * 33. Regression check: Project Compass RAG & SOPs remain intact
 * 34. Regression check: Email Assistant and Copilot remain intact
 */

import {
  ASSESSMENT_QUESTIONS,
  ASSESSMENT_DIMENSIONS,
  calculateDeterministicScores,
} from '../src/data/transformationAssessmentData';
import {
  TRANSFORMATION_ASSESSMENT_SYSTEM_INSTRUCTION,
  parseAndNormalizeTransformationAssessmentJSON,
} from '../server/gemini';
import { detectSensitiveData } from '../src/services/aiService';
import fs from 'fs';
import path from 'path';

let passed = 0;
let failed = 0;

function assert(condition: boolean, testName: string, details?: string) {
  if (condition) {
    console.log(`  ✅ PASS: ${testName}`);
    passed++;
  } else {
    console.error(`  ❌ FAIL: ${testName} ${details ? `— ${details}` : ''}`);
    failed++;
  }
}

async function runPhase5CTests() {
  console.log('===============================================================');
  console.log('  AI BANKER TRANSFORMATION COPILOT — PHASE 5C VERIFICATION');
  console.log('===============================================================\n');

  // -------------------------------------------------------------
  // Test 1: 8 Dimensions defined with weights summing to 1.00
  // -------------------------------------------------------------
  console.log('--- Test 1: Dimension Weights Sum ---');
  const dimensionKeys = Object.keys(ASSESSMENT_DIMENSIONS);
  const totalWeight = Object.values(ASSESSMENT_DIMENSIONS).reduce((sum, d) => sum + d.weight, 0);
  const roundedWeight = Math.round(totalWeight * 100) / 100;
  assert(
    dimensionKeys.length === 8 && roundedWeight === 1.0,
    '1. Exactly 8 dimensions defined and weights sum strictly to 1.00 (100%)',
    `Found ${dimensionKeys.length} dimensions, sum: ${roundedWeight}`
  );

  // -------------------------------------------------------------
  // Test 2: Question bank contains exactly 24 questions (3 per dim)
  // -------------------------------------------------------------
  console.log('\n--- Test 2: Question Bank Composition ---');
  const questionsPerDim = dimensionKeys.map((key) => {
    return ASSESSMENT_QUESTIONS.filter((q) => q.dimensionKey === key).length;
  });
  const allHave3 = questionsPerDim.every((count) => count === 3);
  assert(
    ASSESSMENT_QUESTIONS.length === 24 && allHave3,
    '2. Question bank contains exactly 24 questions (exactly 3 per dimension)',
    `Total: ${ASSESSMENT_QUESTIONS.length}, Per dimension: ${questionsPerDim.join(', ')}`
  );

  // -------------------------------------------------------------
  // Test 3: Deterministic scoring: Lowest answers -> AI Explorer
  // -------------------------------------------------------------
  console.log('\n--- Test 3: Deterministic Scoring (Lowest Band) ---');
  const lowestAnswers = ASSESSMENT_QUESTIONS.map((q) => ({
    questionId: q.id,
    optionId: q.options[0].id,
  }));
  const lowestResult = calculateDeterministicScores(lowestAnswers);
  assert(
    lowestResult.overallScore <= 24 && lowestResult.maturityLevel === 'AI Explorer',
    '3. Lowest choices calculate overall score in 0–24 band and maturity level "AI Explorer"',
    `Score: ${lowestResult.overallScore}, Level: ${lowestResult.maturityLevel}`
  );

  // -------------------------------------------------------------
  // Test 4: Deterministic scoring: Highest answers -> Transformation Leader
  // -------------------------------------------------------------
  console.log('\n--- Test 4: Deterministic Scoring (Highest Band) ---');
  const highestAnswers = ASSESSMENT_QUESTIONS.map((q) => ({
    questionId: q.id,
    optionId: q.options[q.options.length - 1].id, // 100 pts
  }));
  const highestResult = calculateDeterministicScores(highestAnswers);
  assert(
    highestResult.overallScore === 100 && highestResult.maturityLevel === 'AI Transformation Leader',
    '4. Highest choices calculate overall score 100 and maturity level "AI Transformation Leader"',
    `Score: ${highestResult.overallScore}, Level: ${highestResult.maturityLevel}`
  );

  // -------------------------------------------------------------
  // Test 5: Deterministic scoring: Balanced intermediate answers
  // -------------------------------------------------------------
  console.log('\n--- Test 5: Deterministic Scoring (Intermediate Band) ---');
  const intermediateAnswers = ASSESSMENT_QUESTIONS.map((q, idx) => ({
    questionId: q.id,
    optionId: idx % 2 === 0 ? q.options[1].id : q.options[2].id,
  }));
  const intermediateResult = calculateDeterministicScores(intermediateAnswers);
  assert(
    intermediateResult.overallScore > 25 &&
      intermediateResult.overallScore < 75 &&
      (intermediateResult.maturityLevel === 'AI Aware' || intermediateResult.maturityLevel === 'AI Practitioner'),
    '5. Balanced intermediate choices calculate valid intermediate maturity score',
    `Score: ${intermediateResult.overallScore}, Level: ${intermediateResult.maturityLevel}`
  );

  // -------------------------------------------------------------
  // Test 6: Incomplete answers array throws descriptive error
  // -------------------------------------------------------------
  console.log('\n--- Test 6: Incomplete Answers Validation ---');
  let incompleteErrorThrown = false;
  try {
    calculateDeterministicScores(lowestAnswers.slice(0, 20)); // only 20 answers
  } catch (err: unknown) {
    incompleteErrorThrown = true;
  }
  assert(
    incompleteErrorThrown,
    '6. Deterministic scoring engine rejects incomplete answers array (< 24)'
  );

  // -------------------------------------------------------------
  // Test 7: Duplicate question answers rejected
  // -------------------------------------------------------------
  console.log('\n--- Test 7: Duplicate Question Answer Validation ---');
  let duplicateErrorThrown = false;
  try {
    const duplicateAnswers = [...lowestAnswers.slice(0, 23), lowestAnswers[0]];
    calculateDeterministicScores(duplicateAnswers);
  } catch {
    duplicateErrorThrown = true;
  }
  assert(
    duplicateErrorThrown,
    '7. Deterministic scoring engine rejects duplicate question answers'
  );

  // -------------------------------------------------------------
  // Test 8: Sensitive PAN detection
  // -------------------------------------------------------------
  console.log('\n--- Test 8: Sensitive Credit Card PAN Detection ---');
  const panInput = 'Customer account card: 4532 1123 4567 8901 in credit intake';
  assert(
    detectSensitiveData(panInput),
    '8. Sensitive Credit Card PAN pattern is flagged by detectSensitiveData'
  );

  // -------------------------------------------------------------
  // Test 9: Sensitive SSN / Credentials detection
  // -------------------------------------------------------------
  console.log('\n--- Test 9: Sensitive SSN / Credentials Detection ---');
  const ssnInput = 'Banker SSN 123-45-6789 with password SecureP@ssw0rd!';
  assert(
    detectSensitiveData(ssnInput),
    '9. Sensitive SSN and password credentials flagged by detectSensitiveData'
  );

  // -------------------------------------------------------------
  // Test 10: Safe input is not falsely flagged
  // -------------------------------------------------------------
  console.log('\n--- Test 10: Synthetic Input Permitted ---');
  const safeInput = 'Commercial banking team wants to automate loan covenant tracking for Acme Corp.';
  assert(
    !detectSensitiveData(safeInput),
    '10. Synthetic operational prompt passes sensitivity filter without false positives'
  );

  // -------------------------------------------------------------
  // Test 11-17: Server Endpoint & Validation checks
  // -------------------------------------------------------------
  console.log('\n--- Tests 11-17: Server API Endpoint & Architecture ---');
  const serverPath = path.join(process.cwd(), 'server.ts');
  const serverSource = fs.readFileSync(serverPath, 'utf8');

  assert(
    serverSource.includes("app.post(\n    '/api/ai/transformation-assessment'") ||
      serverSource.includes("'/api/ai/transformation-assessment'"),
    '11. Endpoint /api/ai/transformation-assessment is registered in server.ts'
  );

  assert(
    serverSource.includes('/api/ai/transformation-assessment') &&
      serverSource.includes('authenticateFirebaseToken'),
    '12. Endpoint is protected by authenticateFirebaseToken middleware'
  );

  assert(
    serverSource.includes('INVALID_ROLE') &&
      serverSource.includes('INVALID_EXPERIENCE_LEVEL') &&
      serverSource.includes('INVALID_BUSINESS_AREA'),
    '13-15. Server validates required fields: role, experienceLevel, and businessArea'
  );

  assert(
    serverSource.includes('MISSING_ANSWERS') &&
      serverSource.includes('DUPLICATE_QUESTION_ANSWER'),
    '16. Server validates exactly 24 answered questions without duplicates'
  );

  assert(
    serverSource.includes('calculateDeterministicScores(answers)') &&
      serverSource.includes('IMMUTABLE - Gemini cannot alter'),
    '17. Server calculates scores deterministically prior to Gemini invocation'
  );

  // -------------------------------------------------------------
  // Test 18-19: Gemini System Instructions & Prompt Defense
  // -------------------------------------------------------------
  console.log('\n--- Tests 18-19: Gemini System Instructions & Governance ---');
  assert(
    TRANSFORMATION_ASSESSMENT_SYSTEM_INSTRUCTION.includes('ADVISORY') &&
      TRANSFORMATION_ASSESSMENT_SYSTEM_INSTRUCTION.includes('HUMAN-IN-THE-LOOP'),
    '18. System instruction mandates advisory-only guidance and Human-in-the-Loop review'
  );

  assert(
    TRANSFORMATION_ASSESSMENT_SYSTEM_INSTRUCTION.includes('PROMPT INJECTION DEFENSE') &&
      TRANSFORMATION_ASSESSMENT_SYSTEM_INSTRUCTION.includes('DATA ISOLATION'),
    '19. System instruction explicitly enforces prompt injection defense and data isolation'
  );

  // -------------------------------------------------------------
  // Test 20-21: JSON Output Parsing & Normalization
  // -------------------------------------------------------------
  console.log('\n--- Tests 20-21: Output Normalization & Resilient Fallback ---');
  const mockInput = {
    role: 'Commercial Lending Officer',
    experienceLevel: 'Senior (6-10 years)',
    businessArea: 'Commercial & Corporate Banking',
    aiExperience: 'Basic prompts (ChatGPT/Gemini)',
    overallScore: 68,
    maturityLevel: 'AI Advanced Practitioner',
    dimensionScores: highestResult.dimensionScores,
    answeredQuestionsSummary: [],
  };

  const sampleLLMJson = JSON.stringify({
    strengths: ['High awareness of model governance', 'Strong interest in prompt chaining'],
    developmentPriorities: ['Deepen understanding of RAG architectures', 'Automate covenant extraction'],
    roleSpecificRecommendations: ['Partner with credit risk to pilot AI assisted financial spread analysis'],
    quickWins: ['Deploy structured meeting agenda templates with prompt boundaries'],
    governanceFocus: ['Verify maker-checker workflows for all customer facing outputs'],
    recommendedLearningTopics: ['Responsible AI in Banking', 'Prompt Engineering Mastery'],
    recommendedTransformationAreas: ['Commercial Loan Underwriting Intake', 'KYC Document Collation'],
    executiveSummary: 'Demonstrates advanced practitioner proficiency with strong governance alignment.',
  });

  const parsedOutput = parseAndNormalizeTransformationAssessmentJSON(sampleLLMJson, mockInput);
  assert(
    parsedOutput.strengths.length >= 2 &&
      parsedOutput.quickWins.length >= 1 &&
      parsedOutput.executiveSummary.length > 10,
    '20. Parser successfully normalizes raw Gemini JSON response'
  );

  const fallbackOutput = parseAndNormalizeTransformationAssessmentJSON('INVALID_NON_JSON_CORRUPT', mockInput);
  assert(
    fallbackOutput.strengths.length > 0 &&
      fallbackOutput.governanceFocus.length > 0 &&
      fallbackOutput.executiveSummary.includes('Deterministic evaluation indicates'),
    '21. Resilient fallback blueprint generates sound qualitative recommendations on JSON parse error'
  );

  // -------------------------------------------------------------
  // Test 22-26: UI Component Capabilities
  // -------------------------------------------------------------
  console.log('\n--- Tests 22-26: UI Component (TransformationAssessment.tsx) ---');
  const assessmentUiPath = path.join(process.cwd(), 'src/components/TransformationAssessment.tsx');
  const assessmentUiSource = fs.readFileSync(assessmentUiPath, 'utf8');

  assert(
    assessmentUiSource.includes('currentStep') &&
      assessmentUiSource.includes('DIMENSION_KEYS') &&
      assessmentUiSource.includes('Next Dimension'),
    '22. TransformationAssessment.tsx provides 8-dimension multi-step navigation'
  );

  assert(
    assessmentUiSource.includes('ASSESSMENT_QUESTIONS') &&
      assessmentUiSource.includes('handleSelectOption') &&
      assessmentUiSource.includes('pts'),
    '23. TransformationAssessment.tsx renders interactive question cards with points badges'
  );

  assert(
    assessmentUiSource.includes('AI Transformation Scorecard') &&
      assessmentUiSource.includes('overallScore') &&
      assessmentUiSource.includes('Eight Dimension Readiness Breakdown'),
    '24. Results Dashboard displays Overall Score and 8 Dimension meters'
  );

  assert(
    assessmentUiSource.includes('Demonstrated Strengths') &&
      assessmentUiSource.includes('Development Priorities') &&
      assessmentUiSource.includes('Immediate Quick Wins') &&
      assessmentUiSource.includes('Governance, Risk & Compliance Guardrails'),
    '25. Results Dashboard presents full Bento Grid of strengths, priorities, and quick wins'
  );

  assert(
    assessmentUiSource.includes('Assessment is advisory and does not replace professional judgment') &&
      assessmentUiSource.includes('Results should not be used as the sole basis for employment'),
    '26. Advisory and non-decision governance disclaimers are prominently displayed in UI'
  );

  // -------------------------------------------------------------
  // Test 27-28: Dashboard Integration
  // -------------------------------------------------------------
  console.log('\n--- Tests 27-28: Dashboard Integration ---');
  const dashboardPath = path.join(process.cwd(), 'src/components/Dashboard.tsx');
  const dashboardSource = fs.readFileSync(dashboardPath, 'utf8');

  assert(
    dashboardSource.includes("id: 'transformation_assessment'") &&
      dashboardSource.includes("statusText: 'LIVE'") &&
      dashboardSource.includes('<TransformationAssessment'),
    '27. Dashboard.tsx registers Transformation Assessment with LIVE status and active tab'
  );

  assert(
    dashboardSource.includes('overview-launch-assessment-btn'),
    '28. Dashboard Overview quick actions include direct launcher for Transformation Assessment'
  );

  // -------------------------------------------------------------
  // Test 29: Session History Integration
  // -------------------------------------------------------------
  console.log('\n--- Test 29: Session History Integration ---');
  const historyPath = path.join(process.cwd(), 'src/components/SessionHistory.tsx');
  const historySource = fs.readFileSync(historyPath, 'utf8');

  assert(
    historySource.includes("case 'transformation_assessment':") &&
      historySource.includes('Transformation Scorecard') &&
      historySource.includes('value="transformation_assessment"'),
    '29. SessionHistory.tsx supports transformation_assessment filter, icon, and scorecard badge'
  );

  // -------------------------------------------------------------
  // Test 30-31: Firestore Rules & Blueprint
  // -------------------------------------------------------------
  console.log('\n--- Tests 30-31: Firestore Security & Blueprint ---');
  const rulesPath = path.join(process.cwd(), 'firestore.rules');
  const rulesSource = fs.readFileSync(rulesPath, 'utf8');
  assert(
    rulesSource.includes("'transformation_assessment'"),
    '30. firestore.rules validates transformation_assessment in isValidInteraction'
  );

  const blueprintPath = path.join(process.cwd(), 'firebase-blueprint.json');
  const blueprintSource = fs.readFileSync(blueprintPath, 'utf8');
  assert(
    blueprintSource.includes('"transformation_assessment"'),
    '31. firebase-blueprint.json schema registers transformation_assessment'
  );

  // -------------------------------------------------------------
  // Tests 32-34: System Regression Checks
  // -------------------------------------------------------------
  console.log('\n--- Tests 32-34: System Regression Checks ---');
  assert(
    serverSource.includes('/api/ai/process-optimizer') &&
      dashboardSource.includes('<ProcessOptimizer'),
    '32. Regression Check: Process Optimizer module and endpoint remain intact'
  );

  assert(
    serverSource.includes('/api/project-compass/query') &&
      dashboardSource.includes('<ProjectCompassKnowledgeBase'),
    '33. Regression Check: Project Compass RAG knowledge base remains intact'
  );

  assert(
    serverSource.includes('/api/ai/email-assistant') &&
      serverSource.includes('/api/ai/copilot') &&
      serverSource.includes('/api/ai/meeting-prep'),
    '34. Regression Check: Email Assistant, Copilot, and Meeting Prep endpoints remain intact'
  );

  // -------------------------------------------------------------
  // Final Test Results Summary
  // -------------------------------------------------------------
  console.log('\n===============================================================');
  console.log(`  PHASE 5C TEST RESULTS: ${passed} PASSED / ${failed} FAILED (TOTAL: ${passed + failed})`);
  console.log('===============================================================\n');

  if (failed > 0) {
    process.exit(1);
  } else {
    process.exit(0);
  }
}

runPhase5CTests().catch((err) => {
  console.error('Test execution encountered fatal error:', err);
  process.exit(1);
});
